# Inserts a blank line between shell prompts
add_newline = false
command_timeout = 1500

[username]
disabled = true

[hostname]
disabled = true

[git_branch]
truncation_length = 40

[[battery.display]]
threshold = 20

[directory]
truncation_length = 5

